version: '3.8'
services:
  app:
    image: php:8.1-apache
    container_name: php81_app
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devdb
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
